[headers]
  # 为MP3文件设置MIME类型
  [[headers]]
    for = "/*.mp3"
    [headers.values]
      Content-Type = "audio/mpeg"

  # 为WAV文件设置MIME类型
  [[headers]]
    for = "/*.wav"
    [headers.values]
      Content-Type = "audio/wav"
